### ISSUE TITLE
IMPORTANTE

### ISSUE THREAD

**Issue by Ballwictb** [IsraC0d33/Proyecto1Marcas#12]
Ya no hay parte de mis trabajos en jira concretamente estos:>

- Descargar recursos de las marcas conocidas
- Descargar recursos
- Crear header principal 50% beta
- Crear parte del header pequeño 

Alguien sabe algo :)

GRACIAS.

**Comment by MarcosAcedoLlerena** [comment]
yo no he ido lo juro
