### ISSUE TITLE
Aplazo necesario

### ISSUE THREAD

**Issue by Ballwictb** [IsraC0d33/Proyecto1Marcas#14]
La entrega del ultimo sprint es el 15 jueves.

![image](https://github.com/IsraC0d33/Proyecto1Marcas/assets/104717038/26fbd437-32f3-4b74-92fc-bc77ef79064f)

Viendo como hemos trabajado y que nos cuestan ciertas cosas o se nos "atascan" cosa entendible.

Veo necesario (al menos yo ) un aplazo de la entrega.

Que yo recuerde la profe dijo que el **Scrum Master** podía hablar con la profesora y comentarle la situación
para que lo aplazara.

El examen es hasta el 8 (aun no hemos hablado con ella para que lo cambie, por lo de bbdd)

y no creo que sea mucha molestia aplazarlo una semana.

Hablo desde mi perspectiva, si os veis capaces de terminar la pagina para el 15 pues le damos duro y ya.

Si no propongo que el **Scrum Master** que no se quien es la verdad (tantos cambios ya que me he perdido).
Le comente a la profesora mañana 13 (Martes) sobre la situación.

**Comment by MuiGt** [comment]
No se quien es el scrum master, pero si el trabajo no puede estar listo para esta semana y no es la última entrega yo veo factible el hablarlo con ella, solo que alguien diga quien es el scrum máster o asignar uno y punto

**Comment by IsraC0d33** [comment]
el scrum master es marcos

**Comment by Ballwictb** [comment]
Ya no es necesario el plazo,lo terminamos mañana solo falta esta ultima parte: 
![image](https://github.com/IsraC0d33/Proyecto1Marcas/assets/104717038/c00079fa-406f-40b5-ae8b-a21d1ccb5d8d)
👍🏻 

Esta iussee se cerrara a las 10 p.m

**Comment by MuiGt** [comment]
Esa parte si no la tenéis hecha todavía tengo un modelo que nos podría servir, os lo enseño mañana si os parece
