### ISSUE TITLE
Utilización de ramas para el Sprint 3

### ISSUE THREAD

**Issue by IsraC0d33** [IsraC0d33/Proyecto1Marcas#21]
Como estamos trabajando juntos en el desarrollo de la página web y la profesora nos ha pedido que realicemos formularios individuales a partir de esta página (sprint 3), quiero proponer una metodología que nos ayudará a organizar nuestro trabajo de manera más eficiente: utilizar ramas en GitHub.

### ¿Por qué usar ramas?

- Organización: Utilizar ramas nos permitirá trabajar en nuestras funcionalidades individuales de forma separada, evitando conflictos y facilitando la integración posterior.
- Colaboración: Cada uno podrá trabajar en su formulario sin interferir en el trabajo de los demás, pero aun así podremos mantenernos actualizados sobre los avances de todos.
- Control de Versiones: Las ramas nos ofrecen la posibilidad de experimentar con cambios sin afectar la rama principal (main), lo que nos brinda mayor seguridad y control sobre nuestro código.

### ¿Cómo crear una rama en GitHub?

Aquí os dejo un pequeño tutorial gráfico para crear una rama en GitHub:

- Navegar al repositorio: Ingresa a nuestro repositorio en GitHub.
- Seleccionar la rama main: Asegúrate de estar en la rama principal (main).
![imagen](https://github.com/IsraC0d33/Proyecto1Marcas/assets/150441668/c6046e96-6bd8-4d57-9378-b97d6b84ea51)
- Crear una nueva rama: Haz clic en el menú desplegable de la rama y selecciona "Crear nueva rama".
- Nombrar la rama: Asigna un nombre descriptivo para tu rama (por ejemplo, nombre-formulario).
- Crear la rama: Haz clic en el botón para crear la rama.
![imagen](https://github.com/IsraC0d33/Proyecto1Marcas/assets/150441668/f46a1c90-e74a-49a3-abd4-7dacc5f2d694)

Espero que todos estén de acuerdo en adoptar esta metodología para organizar nuestro trabajo. Si tenéis alguna pregunta o sugerencia soy todo oídos.

**Comment by Ballwictb** [comment]
No lo veo mal,buena issue 👌

**Comment by MuiGt** [comment]
Me gusta la idea
