### ISSUE TITLE
FINAL DEL PROYECTO 🫂

### ISSUE THREAD

**Issue by Ballwictb** [IsraC0d33/Proyecto1Marcas#42]
| Israel | Marcos | Andrés | Roberto | Mario  |
|--------|--------|--------|---------|--------|
@IsraC0d33 | @MarcosAcedoLlerena | @MuiGt | @roberto-ortizperez | @MarioGalanEscudero 

👉 🔴

📣 Me complace anunciar que hemos **_terminado_** el proyecto de marcas.

⚔️ A sido difícil, plagado de obstáculos a lo largo del camino que cada uno de nosotros ha debido superar.

💪 Sin embargo creo que cada uno ha logrado sobrepasar sus límites con creces.

💎 Hemos sufrido, hemos disfrutado y hemos aprendido.

🌹 No solo hemos aprendido a usar más o mejor GitHub, sino que también hemos seguido un conjunto de [NORMAS](https://github.com/IsraC0d33/Proyecto1Marcas/blob/main/CODE_OF_CONDUCT.md) 
en este proyecto colaborativo de 6 personas, con el propósito de minimizar cualquier conflicto o diferencia entre nosotros.

🫂 Nos hemos apoyado mutuamente, compartiendo conocimientos y habilidades. 

🍍 Hemos hecho de un proyecto una piña en la que todos nos sintamos parte de ella.

✊ La satisfacción de crear/copiar algo desde la nada. La euforia al alcanzar metas que parecían inalcanzables ha sido mágico.

💞 Hemos experimentado una secuencia de emociones que han desafiado nuestra mente y luego la han relajado.

🫀 La presión y la angustia han estado presentes, pero confío en que la alegría, la tranquilidad y la confianza/seguridad hayan equilibrado esas sensaciones.

🧠 Hemos fusionado seis mentes con ideas, conceptos y perspectivas diferentes para lograr un único propósito.

✨ Después de esta enriquecedora experiencia os propongo una ultima cosa.

📚 Me gustaría que comentéis todos con la siguiente plantilla una cosa que os haya gustado y otra que no.

---
```
✔️ **Me a gustado**:
❌ **No me a gustado**: 
```
---

> [!IMPORTANT]\
> **1️⃣** No quiero peleas ni discusiones en esta issue, si tenéis algo que librar, cosa que veo bien antes que callaros lo que sentís hacedlo en privado como dicta una de nuestras normas.
>
> **2️⃣** Sed sinceros (yo también lo seré), mentir solo hará que nos hagamos mas daño a nosotros mismos y que la persona o personas no sepan si en algo han actuado mal o no.
>
> **3️⃣** Todo lo que vayáis a decir en la plantilla hacerlo desde el respeto, podéis referiros a gente pero no faltar el respeto.

**Si esto a sido posible a sido gracias a ti** 🫵🫵🫵

⭐ **Felicidades.** ⭐

**Comment by Ballwictb** [comment]
✔️ **Me a gustado**: Aprender a usar más Github y como hemos progresado. 
❌ **No me a gustado**: Que haya habido dificultades en determinados momentos del proyecto en los que no ha habido la suficiente comunicación.

**Comment by IsraC0d33** [comment]
✔️ **Me ha gustado**: Las ganas de **continuar** de todos, de **mejorar** constantemente y sobre todo de **aprender** a usar GitHub y aprender a **implementar** y **usar** diferentes **herramientas**, como por ejemplo para analizar código.

❌ **No me ha gustado**: Quizás podríamos haber repartido mejor la parte de cada uno, además de que ha habido numerosos cambios de scrum master.

**Comment by MuiGt** [comment]
Me ha gustado: Aprender a usar GitHub y otras herramientas utilizadas durante el proyecto, además de haber entendido la construcción de la página durante el proceso.

No me ha gustado: podríamos haber repartido el trabajo de una manera más equitativa y haberlo hablado durante el transcurso del tiempo, porque al final solo 4 personas se han hecho casi todo el proyecto y otros no han hecho casi nada, y en lo personal, siento que habría podido ayudar en algo mas pero por falta de tiempo y por falta de comunicación, no ha podido ser así, y eso me molesta.

Pero por lo demás, me alegro de haber formado parte de este equipo y, aunque mi participación ha sido muy baja, ha sido una muy buena experiencia

**Comment by roberto-ortizperez** [comment]
✔️ **Me a gustado**: Haber aprendido un poco mejor como funciona GitHub y cómo es la experiencia de trabajar en equipo.
❌ **No me a gustado**: Que haya habido ocasiones en las que ha faltado comunicación y no estuviese del todo claro como avanzar colectivamente.

**Comment by MarcosAcedoLlerena** [comment]
✔️ Me ha gustado: Haber aprendido a utilizar correctamente el CSS y aprender un poco mas de como funcionan los metas he ir introduciéndome con el JavaScript q
❌ No me ha gustado: La verdad me guaría haber tocado un poco mas el css y que el trabajo hubiera estado mas repartido y no unos hacer tanto y otro poco o nada
