### ISSUE TITLE
Task Tile

### ISSUE THREAD

**Issue by IsraC0d33** [IsraC0d33/Proyecto1Marcas#44]
**What** - description of what you me to do
 Example: Hey @autopilot implement a map of the city of madrid in the index.html file

**Why** - explain why this is important
Example: I want to allow users to see the map of madrid

**Comment by Ballwictb** [comment]
@autopilot quiero que cambies el readme.md y no borres nada sino que añadas una tabla de todos los bots que tenemos


Es importante por que asi la gente sabe de antemano con que bots manejamos

**Comment by Ballwictb** [comment]
@sourcery-ai dime hola


Por que si
