### ISSUE TITLE
Mensaje

### ISSUE THREAD

**Issue by Ballwictb** [IsraC0d33/Proyecto1Marcas#6]
📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍

> Querido equipo,
> 
> Me alegro de que hayamos podido sacar adelante el SPRINT 1 con éxito.
> 
> Sí, ha costado y no ha sido fácil intentar copiar una parte de la página que hemos elegido democráticamente.
> 
> Al final, cada uno ha aportado su grano de arena y eso es lo que cuenta.
> 
> No solo desarrollando, sino también ayudando, motivando, aportando diferentes perspectivas, trayendo felicidad y optimismo.
> 
> Estoy seguro de que podremos enfrentarnos a este reto de forma gratificante.
> 
> Al final, tenemos la responsabilidad/moral de respetar nuestras reglas de conducta.
> 
> Gracias a todos por vuestro arduo trabajo y dedicación.
> 

📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍💡📍

**Comment by IsraC0d33** [comment]
Parece el típico mensaje de copia y pega xdd
