### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by Ballwictb** [IsraC0d33/Proyecto1Marcas#8]
**Describa el fallo**
La implementación del workflow de sonarqube da error por el siguiente motivo:

```
This GitHub Action requires the SONAR_TOKEN env variable.
```

**Reproducir**
Pasos para reproducir el comportamiento:
1. Ir a 'La pestaña Actions'
2. Haga clic en 'SonarQube analysis'
3. Desplácese hasta 'sonarqube.yml y dale click en analysis'
4. Ver error

**Comportamiento esperado**
Lo que tendría que hacer seria en el momento de la ejecución no dar 
errores y que se terminara de ejecutar correctamente. 

**Capturas de pantalla**

![report1](https://github.com/IsraC0d33/Proyecto1Marcas/assets/104717038/45064172-9643-4e48-8e08-4443deaea0ed)

![report2](https://github.com/IsraC0d33/Proyecto1Marcas/assets/104717038/7d4b338a-c75a-4ce8-9cd8-359684b25898)

**Escritorio (complete la siguiente información):**
 - OS: [Windows]
 - Navegador [Brave]
 - Version [v1.62.156]

**Smartphone (por favor, complete la siguiente información):**
No lo he probado en Smartphone (Dará el mismo error)

**Contexto**
He intentado implementar el workflow de sonarqube y me da error por una falta de token.

**Comment by Ballwictb** [comment]
Arreglado

**Comment by IsraC0d33** [comment]
guay
